project:
  type: website
  render: 
    - "!last_year/"
    - "*.qmd"
    - "*.R"
    - "!*draft*"
    
website:
  title: "Mathematics of single-cell omics"
  navbar:
    background: primary
    search: true
    logo: "https://www.bioquant.uni-heidelberg.de/themes/custom/bootstrap_bq/logo.svg"

format:
  html:
    theme: 
      - flatly
      - custom.scss
    css: styles.css
    toc: true
    toc-depth: 3


