project:
  type: website
  render: 
    - "!last_year/"
    - "*.qmd"
    - "*.R"
    - "!*draft*"
website:
  title: "Mathematics of single-cell omics"

format:
  html:
    theme: 
      - cosmo
      - custom.scss
    css: styles.css
    toc: false


